name: Auto pull repo and deploy in server
on:
  push:
    branches: [ "main" ]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Establish SSH connection and run script
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        port: ${{ secrets.PORT }}
        key: ${{ secrets.KEY }}
        script: |
          cd /home/ubuntu/projects/MilvisServer
          git pull
          sudo lsof -t -i tcp:8000 | xargs kill -9
          cd fastapi
          python3 -m gunicorn -k uvicorn.workers.UvicornWorker main:app --daemon --access-logfile ./gunicorn-access.log
